name: Download Docker Image Tar
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull kubeedge/iptables-manager:v1.17.2
          docker save -o iptables-manager-v1.17.2.tar kubeedge/iptables-manager:v1.17.2
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptables-manager-tar
          path: iptables-manager-v1.17.2.tar
